### ISSUE TITLE
permission error

### ISSUE THREAD

**Issue by Panjer23** [Smarity/gap-filling-precipitation-atmosphere-special-issue#1]
i tried to run the mlp code but it says like this
  File "D:\gap-filling-precipitation-atmosphere-special-issue-main\run-mlp-model.py", line 8, in <module>
    model = pickle.load(open("models/mlp__ARJONA.sav", 'rb'))
PermissionError: [Errno 13] Permission denied: 'models/mlp__ARJONA.sav'
would you help me with this error?

**Comment by juanantoniobellido** [comment]
Hi. 

I would need more information so I can help you. 

Which operating system are you using? As it says, there is a permission problem. May the permissions for the model's folder arebe set to admin privileges, which is why Python cannot access the model.

You can try to run the script using admin privileges or allow any user to access the data from the model's folder.

**Comment by Panjer23** [comment]
I am using Windows 11 on my laptop. And I run the script using pycharm community edition. I already try to open pycharm as admin, and also set the security from the models folder to "Full Control" to all
![image](https://user-images.githubusercontent.com/122019060/210770877-4079776c-8e89-452d-9bd2-2c92522867fc.png)

**Comment by juanantoniobellido** [comment]
Please, try the new updated commit.

It has been corrected

**Comment by Panjer23** [comment]
thanks a lot, i'll try it ASAP

**Comment by Panjer23** [comment]
thank you sir, it worked now. although with some minor warnings. i'll configure it out myself.
Again, thanks a lot
